---
title: Assignment #4
authors: Hailey Wellenstein and Zujaja Baig
format: html
editor: visual
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
---

# Introduction to assignment

## Source of data:

[World Bank Databank](https://databank.worldbank.org/reports.aspx?source=2&Topic=1)

## Data cleaning

```{r}
#Data cleaning
library(tidyverse)
library(readxl)
WB_Agriculture_Indicators <- read_excel("data/WB Agriculture Indicators.xlsx", 
                                        sheet = "Data")

WB_Agriculture_Indicators <- WB_Agriculture_Indicators %>%
  rename(series_name = 'Series Name',
         series_code = 'Series Code',
         country = 'Country Name',
         country_code ='Country Code' 
         )

WB_Agriculture_Indicators <- WB_Agriculture_Indicators %>%
  pivot_longer(
    cols = -c(series_name, series_code, country, country_code),
    names_to = "year",
    values_to = "value"
  )

WB_Agriculture_Indicators$year <- as.numeric(WB_Agriculture_Indicators$year)
WB_Agriculture_Indicators$value <- as.numeric(WB_Agriculture_Indicators$value)


```

# First Visualization

```{r}

WB_Agriculture_Indicators %>%
  filter(series_code == "SL.AGR.EMPL.ZS") %>%
  filter(!is.na(value)) %>%
  filter(country == "Mexico" | country == "Guatemala" | country == "Honduras" 
         | country == "Nicaragua" | country == "El Salvador" | country == "Costa Rica" |
           country == "Panama" | country == "Belize") %>%
  ggplot(mapping = aes(x = year, y = value, group = country)) +
        geom_line(mapping = aes(color = country), show.legend = FALSE) +
  facet_wrap(~country) +
  scale_x_continuous(limits = c(2000,2020)) +
  scale_color_manual(values = c("darkgreen", "cadetblue", "darkorange", "brown4", "darkblue", "darkgoldenrod", "darkorchid4", "gray44"))+
  theme_minimal() +
  theme(axis.text.y = element_blank())+
  labs(title = "How has participation in agriculture changed across Central America?",
       subtitle = "Percent of labor force in agriculture, as defined by the International Labor Organization, from 2000-2020",
       x = "Year",
       y = "% in agricultural labor force",
       caption = "Source: World Bank, 2022")
```


# Second Visualization

```{r}
WB_Agriculture_Indicators %>%
  filter(year == 2018) %>%
  filter(series_code == "AG.LND.AGRI.ZS") %>%  
  filter(!is.na(value)) %>%
  filter(country == "Mexico" | country == "Guatemala" | country == "Honduras" 
         | country == "Nicaragua" | country == "El Salvador" | country == "Costa Rica" |
           country == "Panama" | country == "Belize") %>%
  ggplot(mapping = aes(x = country, y = value)) +
  geom_col(fill = "#993300", width = .7) +
  geom_text(aes(label = round(value,1)), vjust = -1, size = 4) +
  theme_minimal() + 
  theme(axis.text.y = element_blank())+
  labs(title = "Percentage of Agricultural Land per Country in Central America",
       subtitle = "Plot shows percentage of agricultural land as defined by the Food and Agriculture Organization, for the year 2018.",
       x=NULL,
       y = "% of Agricultural Land",
       caption = "Source: World Bank, 2022" )
```

# Third Visualization 

```{r}
x <- WB_Agriculture_Indicators %>%
  filter(year == 2018) %>%
  filter(series_code == "AG.LND.AGRI.ZS") %>%
  filter(!is.na(value)) %>%
  pivot_wider(
    names_from = series_code,
    values_from = value
  )   %>%
  select(country, country_code, AG.LND.AGRI.ZS) 

y <- WB_Agriculture_Indicators %>%
  filter(year == 2018) %>%
  filter(series_code == "SL.AGR.EMPL.ZS") %>%
  filter(!is.na(value)) %>%
  pivot_wider(
    names_from = series_code,
    values_from = value
  )   %>%
  select(country, country_code, SL.AGR.EMPL.ZS) 
  

scatterplot_df <- left_join(x = x, y = y, by = "country_code")

scatterplot_df <- scatterplot_df %>% 
  mutate(centam = if_else(
    (country.x == "Mexico" | country.x == "Guatemala" | country.x == "Honduras" 
         | country.x == "Nicaragua" | country.x == "El Salvador" | country.x == "Costa Rica" |
           country.x == "Panama" | country.x == "Belize"),
    true = 1,
    false = 0
  ))

scatterplot_df %>%
  filter(!is.na(SL.AGR.EMPL.ZS)) %>%
  filter(!is.na(AG.LND.AGRI.ZS)) %>%
  ggplot(mapping = aes(
    x= AG.LND.AGRI.ZS, 
    y = SL.AGR.EMPL.ZS,
    color = as.character(centam))) +
  geom_point (aes(shape = centam == 1),size = 2.5, alpha = .8, show.legend = FALSE) +
  geom_text(aes(label = if_else(centam == "1", country_code, "")), show.legend = FALSE, vjust = -1)+
  scale_color_manual(values = c("0" = "gray80", "1" = "dodgerblue4"))+
  theme_minimal()+
  labs( title = "What is the relationship between agricultural employment and land used for agriculture in Central America?",
        subtitle = "Percentage of agricultural land and labor force by country for the year 2018. Definitions of labor force as defined by the International \nLabor Organization and definition of agricultural land as defined by the Food and Agriculture Organization.",
        x = "% of land used for agriculture",
        y = "% of labor force in agriculture",
        caption = "Source: World Bank 2022")

```

# Fourth Visualization

```{r}

my_factor_levels <- c("Nicaragua", "Honduras", "Belize", "Guatemala", "El Salvador", "Costa Rica", "Mexico", "Panama")
WB_Agriculture_Indicators$country <- factor(WB_Agriculture_Indicators$country, levels = my_factor_levels)


WB_Agriculture_Indicators %>%
    filter(year == 2018) %>%
  filter(series_code == "NV.AGR.TOTL.ZS") %>% 
  filter(country == "Mexico" | country == "Guatemala" | country == "Honduras" 
         | country == "Nicaragua" | country == "El Salvador" | country == "Costa Rica" |
           country == "Panama" | country == "Belize") %>%
  filter(!is.na(value)) %>%
  ggplot(mapping = aes(x = country, y = value)) +
  geom_segment(aes(x=country, xend=country, y=0, yend=value), color = "grey") +
  geom_point(size = 3, color = "dodgerblue4")+
  coord_flip() +
  theme_minimal() +
  labs(title = "Central American countries by how much agriculture, forestry, and fishing contribute to GDP.",
       subtitle = "Value added by agriculture, forestry, and fishing as a percent of the country's GDP, for the year 2018.",
       x = NULL,
       y = "Agriculture, forestry, and fishing, value added (% of GDP)",
       caption = "Source: World Bank, 2022"
  )
  
```

